NAME: CIFAR-10
DATA_DIR: ${DATA_DIR}/cifar-10
TRAIN_BATCH_SIZE: ${train.BATCH_SIZE}
TEST_BATCH_SIZE: ${test.BATCH_SIZE}
NUM_SHOTS: ${train.NUM_SHOTS}
NUM_CLASSES: 10
NUM_WORKERS: 6
CLIP_BACKBONE: ${model.CLIP_BACKBONE}
TOPK: 59000