EPOCHS: 100

optimizer:
  NAME: SGD
  LR: 0.01
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5

BATCH_SIZE: 8
NUM_SHOTS: 1
TUNE_IMAGE_ENCODER: True

GPU: 0
FP16: False
PRINT_FREQ: 10
EVAL_FREQ: 200
SEED: 42
CHECKPOINT_DIR: ${OUTPUT_DIR}/checkpoints
